language: emacs-lisp
sudo: false
matrix:
  # Don’t wait for jobs that are allowed to fail
  fast_finish: true
  # Allow snapshot to fail
  allow_failures:
    - env: EMACS_VERSION=snapshot EMACSFLAGS='--eval "(setq byte-compile-error-on-warn t)"'
cache:
  - directories:
      # Cache stable Emacs binaries
      - "$HOME/emacs/"
      # Cache Flycheck dependencies
      - ".cask/"
      # Cache Cask bootstrap dependencies
      - "$HOME/.emacs.d/.cask"
env:
  - EMACS_VERSION=24.3
  - EMACS_VERSION=24.5
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.2
  - EMACS_VERSION=snapshot EMACSFLAGS='--eval "(setq byte-compile-error-on-warn t)"'
before_install:
  # Install a proper Emacs for testing
  - export PATH="$HOME/bin:$PATH"
  - travis_retry wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask
  - emacs --version
  # Install OPAM and OCaml
  - travis_retry wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s "${HOME}/bin" 4.05.0
  - opam init --yes --comp '4.05.0'
  - eval $(opam config env)
install:
  - opam install --yes merlin
  # Install elisp package dependencies, test-only dependencies, and ourselves
  # This uses package.el, so retry in case of transient failure
  - travis_retry cask install
script:
  - make compile
  - make test
